name: relative_time_extract
description: A tool to extract relative time data data from Unicode CLDR.
publish_to: none
version: 1.2.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.17.1
  intl: ^0.18.0
  path: ^1.8.3
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.1
