name: relative_time_extract
description: A tool to extract relative time data data from Unicode CLDR.
publish_to: none
version: 1.2.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  path: ^1.8.2
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
