name: relative_time_example
description: An example relative time project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  relative_time:
    path: ..

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  generate: true