name: relative_time
description: Expresses a DateTime object relative to the current time in text form.
version: 3.0.0
repository: https://github.com/Mosc/relative_time
issues: https://github.com/Mosc/relative_time/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
